package instance

import (
	"html/template"
	"net/http"
)

func (i *Instance) voiceSettingsPage(w http.ResponseWriter, r *http.Request) {
	if _, _, ok := i.authenticated(w, r); !ok {
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	_ = voiceSettingsTemplate.Execute(w, nil)
}

var voiceSettingsTemplate = template.Must(template.New("voice-video-settings").Parse(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Voice &amp; Video — AllChat</title><link rel="stylesheet" href="/assets/app.css"><script src="/assets/app.js" defer></script><script src="/assets/voice-settings-page.js" defer></script></head><body><div class="app-shell"><aside class="community-rail"><a class="community-mark" href="/">AC</a></aside><aside class="channel-sidebar"><div class="community-header">Member Settings</div><nav class="channel-nav settings-nav"><a href="/profile">My Account</a><a href="/voice-video" aria-current="page">Voice &amp; Video</a><div class="voice-section-links"><a href="#voice">Voice</a><a href="#processing">Processing</a><a href="#camera">Camera</a><a href="#advanced">Advanced</a></div><a href="/sessions">Sessions</a><a href="/">Back to Community</a></nav></aside><main class="content-shell"><header class="content-header"><button class="mobile-menu" type="button" data-sidebar-toggle aria-label="Open settings navigation" aria-expanded="false">☰</button><h1>Voice &amp; Video</h1></header><section class="content voice-settings" data-voice-settings>
<header class="voice-settings-intro"><p class="eyebrow">Local media preferences</p><p class="page-description">Choose how you sound and look in Voice Rooms and Direct Calls. Your microphone audio is processed locally.</p></header>
<section class="voice-settings-section" id="voice"><h2>Voice</h2><div class="voice-device-grid"><label>Microphone<select name="microphoneID"><option value="">System default</option></select></label><label>Speaker<select name="speakerID"><option value="">System default</option></select></label></div><div class="setting-row setting-slider"><span><strong>Microphone volume</strong><small>Adjust the level sent to other Members.</small></span><label><output data-input-output></output><input type="range" name="inputGain" min="0" max="2" step="0.05"></label></div><div class="setting-row setting-slider"><span><strong>Speaker volume</strong><small>Adjust all incoming voice audio.</small></span><label><output data-volume-output></output><input type="range" name="outputVolume" min="0" max="1" step="0.05"></label></div><div class="mic-test"><button type="button" data-mic-test>Mic Test</button><div class="mic-meter-bars" data-mic-bars aria-hidden="true"></div><meter min="-80" max="0" value="-80" data-microphone-meter aria-label="Microphone level"></meter></div></section>
<section class="voice-settings-section" id="processing"><h2>Input processing</h2><div class="setting-row"><span><strong>Noise suppression</strong><small>Enhanced uses local RNNoise; Standard uses your browser.</small></span><label class="setting-control"><span class="sr-only">Noise suppression</span><select name="noiseSuppressionMode"><option value="standard">Standard</option><option value="enhanced">Enhanced (RNNoise)</option><option value="off">Off</option></select></label></div><label class="setting-row setting-toggle"><span><strong>Echo cancellation</strong><small>Reduces sound from your speakers returning through the microphone.</small></span><input type="checkbox" name="echoCancellation"></label><label class="setting-row setting-toggle"><span><strong>Automatic gain control</strong><small>Lets WebRTC compensate for microphones that are unusually quiet.</small></span><input type="checkbox" name="autoGainControl"></label><label class="setting-row setting-toggle"><span><strong>Noise gate</strong><small>Closes the microphone when its level stays below the threshold.</small></span><input type="checkbox" name="noiseGate"></label><div class="setting-row setting-slider"><span><strong>Input sensitivity</strong><small>Move right to require a louder sound before opening the gate.</small></span><label><output data-gate-output></output><input type="range" name="noiseGateThresholdDB" min="-80" max="-20" step="1"></label></div></section>
<section class="voice-settings-section" id="camera"><h2>Camera</h2><div class="camera-test"><video data-camera-preview autoplay muted playsinline hidden></video><div class="camera-placeholder" data-camera-placeholder><span>Camera preview is off</span></div><button type="button" data-camera-test>Test Video</button></div><label>Camera<select name="cameraID"><option value="">System default</option></select></label></section>
<section class="voice-settings-section" id="screen-sharing"><h2>Screen sharing</h2><div class="setting-row"><span><strong>Quality mode</strong><small>Auto protects delivery; Text preserves readability; Motion prioritizes smoothness.</small></span><label class="setting-control"><span class="sr-only">Screen share quality</span><select name="screenShareMode"><option value="auto">Auto</option><option value="text">Text</option><option value="balanced">Balanced</option><option value="motion">Motion</option><option value="data-saver">Data saver</option></select></label></div></section>
<section class="voice-settings-section" id="advanced"><h2>Advanced</h2><div class="setting-row"><span><strong>Speaker test</strong><small>Play a short tone through the selected output device.</small></span><button type="button" class="button-secondary" data-output-test>Play sound</button></div><div class="setting-row"><span><strong>Reset Voice &amp; Video settings</strong><small>Restore safe defaults for devices, processing, volume, and screen sharing.</small></span><button type="button" class="button-danger" data-reset-settings>Reset</button></div></section>
<p class="voice-settings-notice" data-voice-notice role="status" aria-live="polite"></p></section></main></div></body></html>`))
