from pathlib import Path
base=Path('/tmp/allchat-login-interactive/desktop/prototypes/login.prototype.html').read_text()
start=base.index(' if(state.signedIn){viewport.innerHTML=')
end=base.index('\n const heading=',start)
base=base[:start]+" if(state.signedIn){renderMain();return;}"+base[end:]
base=base.replace('function render(){',Path('/tmp/main-prototype-ui.js').read_text()+'\nfunction render(){',1)
base=base.replace("function reset(){state=", "function reset(){mainState=mainInitial();state=")
base=base.replace('Signed in — prototype complete','Main conversation')
base=base.replace('AllChat — Login prototype','AllChat — Desktop prototype').replace('Desktop login prototype','Desktop conversation prototype')
base=base.replace('Successful sign-in ends at the prototype completion panel.','Successful sign-in opens #general. Send a local message, toggle members, or search messages with Enter. Settings, voice and attachment flows are future screens.').replace('Fill demo values, then select Sign in. You can also type directly into the fields.','Fill demo values and sign in to open #general. Then type a message or search.').replace('Can you sign in, recover from errors, and move between authentication tabs?','Sign in, send a message, search, and toggle the member list.')
css='''\n.app-viewport .community-shell,.app-viewport .conversation-sidebar{height:calc(var(--demo-height) - 28px)}.app-viewport .content:has(.community-shell){overflow:hidden}.community-shell .lucide-icon{width:20px;height:20px;flex-shrink:0;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.demo-community-name{display:flex;align-items:center;justify-content:space-between}.demo-community-name strong{font-size:16px}.demo-community-name svg{width:16px}.demo-voice-reference{display:flex;gap:8px;padding:6px 9px;color:var(--muted)}.demo-current-member{display:grid;flex:1;margin-left:5px}.demo-current-member strong{font-size:15px}.demo-current-member small{font-size:12px}.demo-header-spacer{flex:1;min-width:0}.demo-header-icon{display:flex;color:var(--muted);padding:7px}.header-search{margin-left:0;position:relative}.header-search>.lucide-icon{position:absolute;left:10px;top:10px;width:18px;height:18px;color:var(--faint);pointer-events:none}.channel-topic{flex:0 1 auto;min-width:0}.conversation-content>header h1{flex-shrink:0}.demo-composer{display:flex;gap:8px;align-self:end;align-items:end;margin:8px 8px 20px;padding:5px;border:1px solid #34363f;border-radius:10px;background:var(--bg-input)}.demo-composer textarea{resize:none;min-height:32px;max-height:120px;padding:6px;border:0;background:transparent;line-height:1.4}.demo-composer button{height:32px;padding:4px 12px;border:0;border-radius:4px;color:white;background:var(--brand)}.conversation-workspace{grid-template-rows:minmax(0,1fr) auto}.demo-member{position:relative;display:flex;align-items:center;gap:10px;padding:7px 8px;color:var(--muted)}.demo-member small{display:block;font-size:10px;color:var(--faint);margin-top:3px}.demo-member .presence-dot{position:absolute;left:30px;top:28px}.main-search-results{overflow:auto}.main-search-results>header{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.main-search-results>header button{background:transparent;border:0;color:var(--muted);font-size:22px}.message:focus{outline:2px solid var(--brand);outline-offset:-2px}.header-button[aria-pressed=true]{background:#30323a;color:var(--text)}\n'''
base=base.replace('</style></head>',css+'</style></head>',1)
Path('/tmp/allchat-login-interactive/desktop/prototypes/main.prototype.html').write_text(base)
